//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rideshare_service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rideshareDBEntities : DbContext
    {
        public rideshareDBEntities()
            : base("name=rideshareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_booking> tbl_booking { get; set; }
        public DbSet<tbl_customer> tbl_customer { get; set; }
        public DbSet<tbl_driver> tbl_driver { get; set; }
        public DbSet<tbl_vehicle> tbl_vehicle { get; set; }
    }
}
