//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rideshare_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_driver
    {
        public int dri_id { get; set; }
        public string dri_fname { get; set; }
        public string dri_lname { get; set; }
        public string dri_address { get; set; }
        public string dri_licence { get; set; }
        public string dri_nic { get; set; }
        public string dri_password { get; set; }
        public byte[] active { get; set; }
    }
}
