//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rideshare_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vehicle
    {
        public int veh_id { get; set; }
        public string veh_regno { get; set; }
        public string veh_type { get; set; }
        public string veh_description { get; set; }
        public string veh_location { get; set; }
        public string veh_driverid { get; set; }
        public string veh_custrequest { get; set; }
        public byte[] active { get; set; }
    }
}
