//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rideshare_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int cusid { get; set; }
        public string cus_fname { get; set; }
        public string cus_lname { get; set; }
        public string cus_phoneno { get; set; }
        public string cus_email { get; set; }
        public string cus_password { get; set; }
        public string active { get; set; }
    }
}
