//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_booking
    {
        public int bk_id { get; set; }
        public Nullable<System.DateTime> bk_time { get; set; }
        public string bk_status { get; set; }
        public Nullable<int> bk_cusid { get; set; }
        public Nullable<int> bk_driverid { get; set; }
        public Nullable<int> bk_vehidid { get; set; }
        public string bk_startloc { get; set; }
        public string bk_endloc { get; set; }
        public string active { get; set; }
    
        public virtual tbl_driver tbl_driver { get; set; }
        public virtual tbl_vehicle tbl_vehicle { get; set; }
        public virtual tbl_customer tbl_customer { get; set; }
    }
}
